#!/usr/bin/perl

sub v2s;

sub resolve_devices;
sub is_enclosure;
sub find_shelves;

sub show_shelf_status;
sub show_disk_status;

sub set_shelf_light;
sub set_disk_light;


if ($#ARGV != 2) {
    print<<EOF;

Usage: shelf_light -s|-d -i|-f|-o|-l device
Where:
	-s	device is shelf (/dev/sgX)
        -d	device is drive (/dev/sgX or /dev/sdX)
	-i	turn on ident light (usually blue)
        -f	turn on failed light (usually red). 
        -o	turn off all lights
        -l	show lights status (for shelf it also show status of drives\' lights)
        device	special device path. For shelf lights it must be SCSI generic for shelf. 
		For drives it can be SCSI generic of block device.

EOF
    exit;
}

# arguments
if    ($ARGV[0] eq "-s") { $shelf_mode = 1 }
elsif ($ARGV[0] eq "-d") { $shelf_mode = 0 }
else {
    print "First argument must be -d or -s\n";
    exit;
}

if    ($ARGV[1] eq "-i") { $op = "ident"  }
elsif ($ARGV[1] eq "-f") { $op = "failed" }
elsif ($ARGV[1] eq "-o") { $op = "off"    }
elsif ($ARGV[1] eq "-l") { $op = "status" }
else {
    print "Second argument must be one of -i, -f, -o or -l\n";
    exit;
}

($dev_no, $shelf_dev) = resolve_devices ($ARGV[2]);

print "$ARGV[2] -> ($dev_no, $shelf_dev)\n";

if ($shelf_dev eq "") {
    print "Your device ($ARGV[2]) is not a shelf and doesn't belong to shelf\n";
    exit;
}

if ($dev_no == -1) {
    print "Failed to find device enclosure position\n";
    exit;
}


if ($shelf_mode) {
    show_shelf_status ($shelf_dev)     if $op eq "status";
    set_shelf_light ($shelf_dev, 1, 2) if $op eq "ident";
    set_shelf_light ($shelf_dev, 2, 1) if $op eq "failed";
    set_shelf_light ($shelf_dev, 0, 0) if $op eq "off";
} else {
    show_disk_status ($shelf_dev, $dev_no) if $op eq "status";
    set_disk_light ($shelf_dev, $dev_no, 1, 2) if $op eq "ident";
    set_disk_light ($shelf_dev, $dev_no, 2, 1) if $op eq "failed";
    set_disk_light ($shelf_dev, $dev_no, 0, 0) if $op eq "off";
}


# by given scsi generic of block device find
# object number in enclosure and scsi generic of
# enclosure which owns device (if given device
# is an enclosure itself, empty string returned)
sub resolve_devices
{
    my ($dev) = @_;

    if ($dev !~ /sg\d+$/) {     # block device. Find it's scsi generic
        open MAP, "sg_map 2>/dev/null |" || die "sg_map not found";
        while (<MAP>) {
            chomp;
            @a = split /\s+/;
            next unless $#a;
            if ($a[1] eq $dev) { $dev = $a[0]; last } 
        }
        close MAP;
    }

    return ("-", $dev) if is_enclosure ($dev);

    # is it a drive in enclosure?
    # 1. find it's SAS address
    $dev =~ /(sg\d+)$/;
    $dev_name = $1;
    $lnk = readlink "/sys/class/scsi_generic/$dev_name/device";

    if ($lnk =~ /\/(end_device-\d+:\d+:\d+)\//) {
        $end = $1;
    } else {
        return (-1, "");
    }

    $sas = `cat /sys/class/sas_end_device/$end/device/sas_device:$end/sas_address`;
    chomp $sas;

    # 2. find all shelves attached
    # 3. find device with such address
    foreach $shelf (find_shelves ()) {
        open SES, "sg_ses -p 0xA $shelf 2> /dev/null |" || die "sg_ses not found";

        $disk = $res_disk = -1;

        while (<SES>) {
            chomp;
            $disk++ if /^\s*Transport protocol/;
            if (/^\s*SAS address: (0x[0-9a-f]+)\s*$/ && $1 eq $sas) {
                $res_disk = $disk;
                last;
            }
        }

        close SES;

        return ($res_disk, $shelf) if $res_disk != -1;
    }
    
    return (-1, "");
}


sub is_enclosure
{
    my ($dev) = @_;

    open SES, "sg_ses $dev 2>/dev/null |" || die "sg_ses utility not found";

    while (<SES>) {
        return 1 if /enclosure services device/;
    }

    close MAP;
    return 0;
}


sub find_shelves
{
    my @res;
    open SCSI, "/proc/scsi/scsi" || die "You must have /proc/scsi/scsi to run this!";

    $sg = -1;
    while (<SCSI>) {
        chomp;
        $sg++ if (/^Host:/);
        push @res, "/dev/sg$sg" if (/^\s*Type:\s+Enclosure/);
    }

    close SCSI;

    return @res;
}


sub show_shelf_status
{
    my ($dev) = @_;
    my $state = 0;
    my ($ident, $fail) = (0, 0);

    open SES, "sg_ses -p 2 $dev 2> /dev/null |";

    while (<SES>) {
        chomp;
        $state = 1 if $state == 0 && (/^\s*Element type: Enclosure,/);
        $state = 2 if $state == 1 && /^\s*Element 1 status/;
        
        if ($state == 2 && /Ident=(\d+).*Failure indication=(\d+)/) {
            $ident = $1;
            $fail = $2;
            last;
        }
    }

    close SES;

    print "ident=$ident fail=$fail\n";
}


sub show_disk_status
{
    my ($dev, $disk) = @_;
    my $state = 0;
    my ($ident, $fail) = (0, 0);

    open SES, "sg_ses -p 2 $dev 2> /dev/null |";

    while (<SES>) {
        chomp;
        $state = 1 if $state == 0 && /^\s*Element type: Array device/;
        $state = 2 if $state == 1 && /^\s*Element (\d+) status/ && $1 == $disk+1;
        
        if ($state == 2 && /RMV=(\d+).*Ident=(\d+)/) {
            $ident = $2;
            $fail = $1;
            last;
        }
    }

    close SES;

    print "ident=$ident fail=$fail\n";
}


sub set_shelf_light
{
    my ($dev, $ident, $fail) = @_;
    my $raw, $cards;

    $cards = 0;
    foreach $_ (`sg_ses -p 2 $dev`) {
        chomp;
        $cards++ if (/^\s*Element \d+ status:/);

        if (/^\s*Element type:/) {
            last if (/Enclosure,/);
            $cards++;
        }
    }

    # skip generation code and overall page
    $cards += 2;

    # each card is 4 bytes long
    $cards *= 4;

    $raw = `sg_ses -p 2 -r $dev`;
    $raw =~ s/^\s*//;
    @raw = split /\s+/, $raw;

    $raw[$cards] = v2s (hex ($raw[$cards]) | 0x80);

    # ident light
    $val = hex ($raw[$cards+1]);
    if    ($ident == 0) { $val &= 0x7F  }
    elsif ($ident == 1) { $val |= 0x80 }
    $raw[$cards+1] = v2s ($val);

    # fail light
    $val = hex ($raw[$cards+2]);
    if    ($fail == 0) { $val &= 0xFD }
    elsif ($fail == 1) { $val |= 0x02  }
    $raw[$cards+2] = v2s ($val);

    $r = join " ", @raw;
    system ("echo $r | sg_ses -p 2 -c -d - -r $dev >/dev/null");
}


sub set_disk_light
{
    my ($dev, $disk, $ident, $fail) = @_;
    my $raw, $cards;

    # skip generation code and overall page
    $cards = 2 + $disk;

    print "$cards\n";
    # each card is 4 bytes long
    $cards *= 4;

    $raw = `sg_ses -p 2 -r $dev`;
    $raw =~ s/^\s*//;
    @raw = split /\s+/, $raw;

    $raw[$cards] = v2s (hex ($raw[$cards]) | 0x80);

    # ident light
    $val = hex ($raw[$cards+2]);
    if    ($ident == 0) { $val &= 0xFD  }
    elsif ($ident == 1) { $val |= 0x02 }
    # fail light
    if    ($fail == 0) { $val &= 0xFB }
    elsif ($fail == 1) { $val |= 0x04  }
    $raw[$cards+2] = v2s ($val);

    $r = join " ", @raw;
    print "$r\n";
    system ("echo $r | sg_ses -p 2 -c -d - -r $dev >/dev/null");
}


sub v2s
{
    return sprintf "%02x", $_[0];
}
